title: Boniface Nwanganga
logo: new_passport.jpg
description: A data analyst with experience using Excel for data analysis, SQL for data interrogation and manipulation and Power Bi for creating business intelligent report and visualisation.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
